services:
  rapida_jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./create_user.sh:/app/create_user.sh
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./jupyterhub_config.py:/app/jupyterhub_config.py
      - ./Makefile:/app/Makefile
      - ./rapida_jupyter:/app/rapida_jupyter # mount app folder to container
      - ./notebooks:/app/notebooks # mount notebooks folder to container
      # uncomment to mount token info from local
      # - ~/.rapida:/root/.rapida
      # uncomment to mount data folder from local
      # - ./data:/data
    entrypoint: "/app/entrypoint.sh"
    ports:
      - 8100:8000
    env_file:
      - .env
